services:
  postgres:
    image: postgres:13.10-alpine
    container_name: postgres
    ports:
      - "${PG_PORT}:5432"
    networks:
      - common-network
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - common-network
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    
networks:
  common-network:
    driver: bridge

volumes:
  postgres-data:
